# Generated by Django 5.0.3 on 2024-03-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias_app', '0002_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias_imagenes/'),
        ),
    ]
