# Generated by Django 5.0.3 on 2024-03-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias_app', '0004_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='contenido',
        ),
    ]
